### ISSUE TITLE
Concatenation issue

### ISSUE THREAD

**Issue by nmarshall** [asifmuh91/NumericConversion#1]
**Input:** `The database has 66723107008 records.`
**Returns:** `sixty-six billion, seven hundred and twenty-three million, one hundred seven thousand eight`

**Expected:** sixty-six billion, seven hundred and twenty-three million, one hundred __and__
seven thousand __and__ eight

**Comment by asifmuh91** [comment]
Please check latest commit. I should have added 'and' to number digits and remove space after that. Let me know if any questions
Asif
